version: "3.9"

services:
  app:
    build:
    # use the current directory as the build context  
      context: .
      args:
        - DEV=true
    ports:
      - 8050:8050
    volumes:
      - ./app:/app

    command: >
      sh -c "python manage.py runserver 0.0.0.0:8050"
